# Time in minutes after exploding blocks should regenerate
regenDelay: 5.0

# Maximum time in milliseconds that can be spent per tick placing blocks. (50 milliseconds per tick).
# Setting this higher will result in lag spikes
placementIntensity: 5

# Blocks blown up by these entities will not be affected by this plugin
# For a complete list of entity types, see https://papermc.io/javadocs/org/bukkit/entity/EntityType.html
ignoredEntities:
# - PRIMED_TNT