# Time in minutes after exploding blocks should regenerate
regen_delay: 5.0

# Maximum time in milliseconds that can be spent per tick placing blocks. (50 milliseconds per tick).
# Setting this higher will result in lag spikes
placement_intensity: 5

# Blocks blown up by these entities will not be affected by this plugin
# For a complete list of entity types, see https://papermc.io/javadocs/paper/1.14/org/bukkit/entity/EntityType.html
ignored_entities:
# - PRIMED_TNT

# Blocks with these materials which are blown up will be ignored
# For a complete list of materials, see https://papermc.io/javadocs/paper/1.14/org/bukkit/Material.html
ignored_materials:
# - TNT

# Only blocks with these materials which are blown up will be regenerated.
# When this list is empty, all blocks will be.
# For a complete list of materials, see https://papermc.io/javadocs/paper/1.14/org/bukkit/Material.html
included_materials:
# - GRASS
