# Updated config: https://github.com/MicleBrick/ExplosionRegen/blob/master/src/main/resources/config.yml

# Time in minutes after exploding blocks should regenerate
regen_delay: 1.0

# Maximum time in milliseconds that can be spent per tick placing blocks. (50 milliseconds per tick).
# Setting this higher will result in lag spikes
placement_intensity: 5

# Blocks blown up by these entities will not be affected by this plugin
ignored_entity_explosions:
# - PRIMED_TNT

# Entities of these types will not be regenerated
# For a complete list of entity types, see https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/EntityType.html
ignored_entities:
# - ARMOR_STAND

# Additional entities to regenerate when blown up
# For a complete list of entity types, see https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/EntityType.html
included_entities:
# - SHEEP

# Blocks with these materials which are blown up will be ignored
# For a complete list of materials, see https://papermc.io/javadocs/paper/1.16/org/bukkit/Material.html
ignored_materials:
# - TNT

# Only blocks with these materials which are blown up will be regenerated.
# When this list is empty, all blocks will be.
# For a complete list of materials, see https://papermc.io/javadocs/paper/1.16/org/bukkit/Material.html
included_materials:
# - GRASS
