name: ExplosionReversal
version: 4.0.1
main: net.starlegacy.explosionreversal.ExplosionReversalPlugin
authors: ["MicleBrick", "SijmenSchoon", "rsammelson"]
api-version: "1.16"
commands:
  regen:
    permission: explosionreversal.regen
