name: ExplosionReversal
version: "NULL"
main: net.starlegacy.explosionreversal.ExplosionReversalPlugin
authors: ["MicleBrick", "PeterCrawley", "SijmenSchoon", "rsammelson"]
api-version: 1.18
commands:
  regen:
    permission: explosionreversal.regen
  explosionreversalreload:
    permission: explosionreversal.reload
