name: ExplosionRegen
version: 3.0.0
main: net.starlegacy.explosionregen.ExplosionRegenPlugin
authors: ["MicleBrick", "SijmenSchoon", "rsammelson"]
api-version: "1.15"
commands:
  regen:
    permission: explosionregen.regen
