name: ExplosionReversal
version: 5.0.0
main: net.starlegacy.explosionreversal.ExplosionReversalPlugin
authors: ["MicleBrick", "SijmenSchoon", "rsammelson"]
api-version: "1.16"
commands:
  regen:
    permission: explosionreversal.regen
